'use strict';

const { test } = require('node:test');
const assert = require('node:assert/strict');
const itv2 = require('../src/dsc-itv2');
const fixture = require('./fixtures/dsc-itv2-transcript.json');

// test/fixtures/dsc-itv2-transcript.json was generated by running the
// reference Python implementation (LawPaul/HA_DSC_Neo_ITv2) with fixed
// randomness: a full handshake + notifications + outbound commands, for both
// encryption types. The Node port must produce identical bytes.

// Python field values → the shapes our decoder produces
function normalize(v) {
  if (Buffer.isBuffer(v)) return v.toString('hex')
  if (Array.isArray(v)) return v.map(normalize)
  if (v && typeof v === 'object') {
    if ('year' in v && 'month' in v && 'second' in v) {
      const p = (n) => String(n).padStart(2, '0')
      return `${v.year}-${p(v.month)}-${p(v.day)}T${p(v.hour)}:${p(v.minute)}:${p(v.second)}`
    }
    return Object.fromEntries(Object.entries(v).filter(([k]) => k !== 'deserialization_error').map(([k, x]) => [k, normalize(x)]))
  }
  return v
}

test('CRC-16-CCITT matches the reference', () => {
  assert.equal(itv2.crc16(Buffer.from('123456789')), fixture.crc_123456789)
})

test('TLink stuffing round-trips the reserved bytes', () => {
  const raw = Buffer.from([0x01, 0x7d, 0x7e, 0x7f, 0x02])
  assert.deepEqual(itv2.unstuff(itv2.stuff(raw)), raw)
  assert.equal(itv2.stuff(raw).indexOf(0x7e), -1)
  assert.throws(() => itv2.unstuff(Buffer.from([0x7d, 0x05])), /escape/)
})

for (const t of fixture.transcripts) {
  test(`ITv2 Type ${t.encryption_type}: handshake, notifications and commands match the reference byte-for-byte`, () => {
    const codecRandom = Buffer.from(t.random_calls[1], 'hex') // call 0 was the simulated panel's
    const codec = new itv2.SessionCodec(
      { integration_id: t.integration_id, type1_access_code: t.type1_access_code, type2_access_code_hex: t.type2_key },
      { random: (n) => { assert.equal(n, codecRandom.length); return codecRandom } },
    )
    for (const step of t.steps) {
      const events = codec.feed(Buffer.from(step.in, 'hex'))
      const failed = events.find((e) => e.type === 'failed')
      assert.equal(failed, undefined, `${step.note}: ${failed?.reason}`)
      const out = events.filter((e) => e.type === 'send').map((e) => e.data.toString('hex'))
      assert.deepEqual(out, step.out, `${step.note}: outbound bytes`)
      const evs = events.filter((e) => e.type !== 'send')
      assert.equal(evs.length, step.events.length, `${step.note}: event count`)
      evs.forEach((e, i) => {
        const ref = step.events[i]
        assert.equal(e.type, ref.type, step.note)
        if (e.type === 'connected') {
          assert.equal(e.session_id, ref.session_id)
          assert.equal(e.encryption_type, ref.encryption_type)
          assert.deepEqual(e.fw, ref.fw)
        } else {
          assert.equal(e.command, ref.command, step.note)
          assert.deepEqual(normalize(e.decoded), ref.decoded, `${step.note}: decoded`)
        }
      })
    }
    assert.equal(codec.isReady, true)
    const build = {
      Poll: { _type: 'ConnectionPoll' },
      ReqCapabilities: { _type: 'CommandRequestMessage', request: { _type: 'ConnectionSystemCapabilities' } },
      ReqZones: { _type: 'CommandRequestMessage', request: { _type: 'ModuleZoneStatus', zone_start: 1, zone_count: 32, status_size_in_bytes: 1, zone_status_bytes: [] } },
      ReqPartition: { _type: 'CommandRequestMessage', request: { _type: 'ModulePartitionStatus', partition: 1 } },
      ReqLabels: { _type: 'CommandRequestMessage', request: { _type: 'NotificationLabelText', collection: 0xd1, start: 1, end: 8, labels: [] } },
      ArmAway: { _type: 'PartitionArm', partition: 1, arm_mode: 2, access_code: '1234' },
      Disarm: { _type: 'PartitionDisarm', partition: 1, access_code: '1234' },
      Bypass: { _type: 'SingleZoneBypassWrite', partition: 1, zone_number: 5, bypass_state: 1 },
      End: { _type: 'ConnectionEndSession' },
    }
    for (const s of t.sends) {
      assert.equal(codec.sendMessage(build[s.note]).toString('hex'), s.out, `send ${s.note}`)
    }
  })
}

test('ITv2: wrong Type 2 key or a corrupted frame fails cleanly', () => {
  const t = fixture.transcripts[0]
  const random = Buffer.from(t.random_calls[1], 'hex')
  const codec = new itv2.SessionCodec({ type2_access_code_hex: 'ff'.repeat(16) }, { random: () => random })
  let failed = null
  for (const step of t.steps) {
    const ev = codec.feed(Buffer.from(step.in, 'hex')).find((e) => e.type === 'failed')
    if (ev) { failed = ev; break }
  }
  assert.ok(failed, 'a wrong key must not reach READY')
  const bad = Buffer.from(t.steps[0].in, 'hex')
  bad[bad.length - 3] ^= 0xff // corrupt the CRC
  const ev = new itv2.SessionCodec({}).feed(bad)
  assert.match(ev.find((e) => e.type === 'failed').reason, /CRC|escape|delimiter/)
})

test('ITv2: zone and partition status bytes decode', () => {
  assert.deepEqual(itv2.decodeZoneByte(0x81), { open: true, tamper: false, fault: false, lowBattery: false, delinquency: false, alarm: false, alarmMemory: false, bypass: true })
  const p = itv2.decodePartitionStatus([0x05, 0x02, 0x00])
  assert.equal(p.armed, true)
  assert.equal(p.armMode, 'away')
  assert.equal(p.trouble, true)
  assert.equal(itv2.decodePartitionStatus([0x02]).ready, true)
})
