const http         = require('http');
const https        = require('https');
const express      = require('express');
const path         = require('path');
const cookieParser = require('cookie-parser');
require('./src/logger').install(); // must be first — patches console before any other module logs
const loadConfig      = require('./config');
const auth            = require('./src/auth');
const acme            = require('./src/acme');
const DataStore       = require('./src/data-store');
const ConnectionManager = require('./src/connection-manager');
const RelayController   = require('./src/relay-controller');
const SensorRegistry    = require('./src/sensor-registry');
const createApiRoutes   = require('./src/api-routes');
const setupWebSocket    = require('./src/websocket');

function tryRequire(mod, hint) {
  try { return require(mod); }
  catch { console.warn(`[Server] Optional module unavailable: ${mod}${hint ? ' — ' + hint : ''}`); return null; }
}

async function main() {
  const config          = loadConfig();
  const store           = new DataStore();
  store.startPersistence(); // restore saved sensor data + history, save every 5 min and on shutdown
  const connectionMgr   = new ConnectionManager(config, store);
  const relayController = new RelayController(config, store);
  const sensorRegistry  = new SensorRegistry(store, config.language); // server-side label translation

  // Start optional integrations before wiring API routes so unifiProtect is available
  let satelClient = null;
  if (config.satel?.host) {
    const SatelClient = tryRequire('./src/satel-client');
    if (SatelClient) {
      satelClient = new SatelClient(config, store, sensorRegistry);
      satelClient.start().catch((err) => console.error(`[Satel] Start failed: ${err.message}`));
    }
  }

  let unifiProtect = null;
  if (config.unifi?.host) {
    const UnifiProtectClient = tryRequire('./src/unifi-protect-client');
    if (UnifiProtectClient) {
      unifiProtect = new UnifiProtectClient(config, store, sensorRegistry);
      unifiProtect.start().catch((err) => console.error(`[UniFi Protect] Start failed: ${err.message}`));
    }
  }

  // Always construct — the client reads cameras from config.json on demand, so
  // cameras added via Settings apply live without a restart.
  let reolink = null;
  const ReolinkClient = tryRequire('./src/reolink-client');
  if (ReolinkClient) {
    reolink = new ReolinkClient();
    const n = reolink.getCameras().length;
    if (n) console.log(`[Reolink] ${n} camera(s) configured`);
  }

  let mqttExplorer = null;
  if (config.mqtt?.host) {
    const MqttExplorer = tryRequire('./src/mqtt-explorer');
    if (MqttExplorer) mqttExplorer = new MqttExplorer(config);
  }

  // SIP doorbell intercom — pulses the configured door relay on "open door"
  let sipServer = null;
  if (config.sip?.enabled) {
    const SipServer = tryRequire('./src/sip-server', 'run: npm install sip');
    if (SipServer) {
      sipServer = new SipServer(config, {
        onOpenDoor: async () => {
          const idx = config.sip.doorRelay;
          if (idx == null) throw new Error('No door relay configured');
          await relayController.setState(idx, true);
          const pulse = config.sip.doorPulseMs || 3000;
          if (pulse > 0) {
            setTimeout(() => relayController.setState(idx, false).catch(() => {}), pulse);
          }
        },
      });
    }
  }

  // ── Determine HTTPS mode ─────────────────────────────────────────────────
  const leEnabled     = !!(config.server?.letsEncrypt?.enabled);
  const httpsEnabled  = !!(config.server?.https?.enabled);
  const isSecure      = leEnabled || httpsEnabled;

  // ── Express app ──────────────────────────────────────────────────────────
  const app = express();
  app.use(cookieParser());

  // React dashboard — public static files (API calls are Bearer-token protected)
  const reactDist = path.join(__dirname, 'react-dashboard', 'dist');
  app.use('/react', express.static(reactDist));
  app.get('/react/*', (req, res) => res.sendFile(path.join(reactDist, 'index.html')));

  app.use(auth.middleware(isSecure));
  app.use(express.json());
  // Swagger UI for the REST API (spec generated by scripts/gen-openapi.js).
  // Auth-gated like the rest of the UI. The spec is injected inline so the page
  // needs no separate (unauthenticated) fetch of /openapi.json — the reason a
  // token-authed page would otherwise hang on "loading".
  app.get('/api-docs', (req, res) => {
    const fs = require('fs');
    try {
      const html = fs.readFileSync(path.join(__dirname, 'public', 'api-docs.html'), 'utf8');
      const spec = fs.readFileSync(path.join(__dirname, 'public', 'openapi.json'), 'utf8');
      // Escape "<" so an embedded "</script>" can't break out of the tag.
      const safe = spec.replace(/</g, '\\u003c');
      res.type('html').send(html.replace('__OPENAPI_SPEC__', safe));
    } catch (err) {
      res.status(500).send('API docs unavailable — run: npm run openapi');
    }
  });
  app.use(express.static(path.join(__dirname, 'public')));
  let ffmpegRtsp = null;
  if (config.ffmpegRtsp?.enabled) {
    const FFmpegRTSP = tryRequire('./src/ffmpeg-rtsp');
    if (FFmpegRTSP) {
      ffmpegRtsp = new FFmpegRTSP(config);
      ffmpegRtsp.start();
    }
  }

  // Automation engine (rules / scenes / notifications) — io attached after WS setup
  let automation = null;
  const AutomationEngine = tryRequire('./src/automation-engine');
  if (AutomationEngine) automation = new AutomationEngine(store, sensorRegistry, relayController);

  const apiClients = { unifiProtect, reolink, mqttExplorer, auth, isSecure, ffmpegRtsp, automation, sipServer };
  app.use('/api', createApiRoutes(store, relayController, sensorRegistry, connectionMgr, apiClients));

  // ── Build HTTP/HTTPS server ───────────────────────────────────────────────
  let mainServer;
  let mainPort;

  if (leEnabled) {
    // Let's Encrypt: obtain cert first, then start HTTPS + redirect
    let certs = null;
    try {
      certs = await acme.acquireCert(config);
    } catch (err) {
      console.error(`[ACME] Certificate acquisition failed: ${err.message} — falling back to HTTP`);
    }
    if (certs) {
      mainServer = https.createServer({ cert: certs.cert, key: certs.key }, app);
      mainPort   = config.server?.letsEncrypt?.port || 443;
      acme.startRedirectServer(mainPort);
      acme.scheduleRenewal(config, (renewed) => {
        mainServer.setSecureContext({ cert: renewed.cert, key: renewed.key });
        console.log('[ACME] Certificate renewed and hot-reloaded');
      });
    } else {
      mainServer = http.createServer(app);
      mainPort   = config.server?.port || 3001;
    }
  } else if (httpsEnabled) {
    // Manual cert files
    const httpsServer = acme.createHttpsServerFromConfig(app, config);
    if (httpsServer) {
      mainServer = httpsServer;
      mainPort   = config.server?.https?.port || 3443;
      // Optional HTTP redirect on the plain port
      const plainPort = config.server?.port;
      if (plainPort && plainPort !== mainPort) {
        const redirect = http.createServer((req, res) => {
          const host = (req.headers.host || '').split(':')[0];
          const dest = mainPort === 443
            ? `https://${host}${req.url}`
            : `https://${host}:${mainPort}${req.url}`;
          res.writeHead(301, { Location: dest }).end();
        });
        redirect.listen(plainPort, () =>
          console.log(`[Server] HTTP redirect on :${plainPort} → HTTPS :${mainPort}`)
        );
      }
    } else {
      console.warn('[Server] HTTPS configured but could not create HTTPS server — falling back to HTTP');
      mainServer = http.createServer(app);
      mainPort   = config.server?.port || 3001;
    }
  } else {
    mainServer = http.createServer(app);
    mainPort   = config.server?.port || 3001;
  }

  const io = setupWebSocket(mainServer, store, sensorRegistry, connectionMgr, auth, sipServer);

  if (automation) {
    automation.setIo(io);
    automation.start();
  }

  if (mqttExplorer) {
    mqttExplorer.setIo(io);
    mqttExplorer.start();
  }

  // Wire relay controller to whichever source is currently active
  connectionMgr.on('source-changed', () => {
    relayController.setClient(connectionMgr.getActiveClient());
  });

  // Start the connection manager (handles MQTT → VRM fallback automatically)
  await connectionMgr.start();
  relayController.setClient(connectionMgr.getActiveClient());

  // Start SIP doorbell intercom if enabled
  if (sipServer) {
    try {
      sipServer.start();
    } catch (err) {
      console.error(`[SIP] Start failed: ${err.message}`);
    }
  }

  // Start SolarEdge client if configured
  if (config.solaredge?.siteId && config.solaredge?.apiKey) {
    const SolarEdgeClient = tryRequire('./src/solaredge-client');
    if (SolarEdgeClient) {
      const solarEdge = new SolarEdgeClient(config, store);
      solarEdge.start().catch((err) => console.error(`[SolarEdge] Start failed: ${err.message}`));
    }
  }

  // Start SmartThings client if configured
  if (config.smartthings?.token) {
    const SmartThingsClient = tryRequire('./src/smartthings-client');
    if (SmartThingsClient) {
      const smartThings = new SmartThingsClient(config, store, sensorRegistry);
      smartThings.start().catch((err) => console.error(`[SmartThings] Start failed: ${err.message}`));
    }
  }

  // Start BoneIO client if configured
  if (config.boneio) {
    const BoneIOClient = tryRequire('./src/boneio-client');
    if (BoneIOClient) {
      const boneio = new BoneIOClient(config, store, sensorRegistry);
      boneio.start();
    }
  }

  // Start Dirigera (IKEA) client if configured
  if (config.dirigera?.host && config.dirigera?.token) {
    const DirigeraClient = tryRequire('./src/dirigera-client');
    if (DirigeraClient) {
      const dirigera = new DirigeraClient(config, store, sensorRegistry);
      dirigera.start().catch((err) => console.error(`[Dirigera] Start failed: ${err.message}`));
    }
  }

  // Start Tradfri (IKEA) client if configured
  if (config.tradfri?.host) {
    const TradfriClient = tryRequire('./src/tradfri-client', 'npm install node-tradfri-client');
    if (TradfriClient) {
      const tradfri = new TradfriClient(config, store, sensorRegistry);
      tradfri.start().catch((err) => console.error(`[Tradfri] Start failed: ${err.message}`));
    }
  }

  // Start ESPHome client if devices are configured
  if (config.esphome?.devices?.length) {
    const ESPHomeClient = tryRequire('./src/esphome-client');
    if (ESPHomeClient) {
      const esphome = new ESPHomeClient(config, store, sensorRegistry);
      esphome.start().catch((err) => console.error(`[ESPHome] Start failed: ${err.message}`));
    }
  }

  // Start Shelly client if devices are configured
  if (config.shelly?.devices?.length) {
    const ShellyClient = tryRequire('./src/shelly-client');
    if (ShellyClient) {
      const shelly = new ShellyClient(config, store, sensorRegistry);
      shelly.start().catch((err) => console.error(`[Shelly] Start failed: ${err.message}`));
    }
  }

  // Start Dreame client if configured
  if (config.dreame?.devices?.length) {
    const DreameClient = tryRequire('./src/dreame-client');
    if (DreameClient) {
      const dreame = new DreameClient(config, store, sensorRegistry);
      dreame.start().catch((err) => console.error(`[Dreame] Start failed: ${err.message}`));
    }
  }

  // Start MC6 thermostat client if configured
  if (config.mc6?.broker && config.mc6?.devices?.length) {
    const MC6Client = tryRequire('./src/mc6-client');
    if (MC6Client) {
      const mc6 = new MC6Client(config, store, sensorRegistry);
      mc6.start().catch((err) => console.error(`[MC6] Start failed: ${err.message}`));
    }
  }

  // Start Roborock client if configured
  if (config.roborock?.devices?.length) {
    const RoborockClient = tryRequire('./src/roborock-client');
    if (RoborockClient) {
      const roborock = new RoborockClient(config, store, sensorRegistry);
      roborock.start().catch((err) => console.error(`[Roborock] Start failed: ${err.message}`));
    }
  }

  // Start BroadLink IR/RF client if configured
  if (config.broadlink?.devices?.length) {
    const BroadlinkClient = tryRequire('./src/broadlink-client');
    if (BroadlinkClient) {
      const broadlink = new BroadlinkClient(config, store, sensorRegistry);
      apiClients.broadlink = broadlink;
      broadlink.start().catch((err) => console.error(`[Broadlink] Start failed: ${err.message}`));
    }
  }

  // Start Waveshare Modbus TCP client if configured
  if (config.waveshare?.devices?.length) {
    const WaveshareClient = tryRequire('./src/waveshare-modbus-client');
    if (WaveshareClient) {
      const waveshare = new WaveshareClient(config, store, sensorRegistry);
      waveshare.start().catch((err) => console.error(`[Waveshare] Start failed: ${err.message}`));
    }
  }

  // Start LG ThinQ client if configured (token-based — no credentials needed)
  if (config.lgthinq) {
    const LGThinQClient = tryRequire('./src/lgthinq-client');
    if (LGThinQClient) {
      const lgthinq = new LGThinQClient(config, store, sensorRegistry);
      lgthinq.start().catch((err) => console.error(`[LGThinQ] Start failed: ${err.message}`));
    }
  }

  // Start Somfy client if configured (cloud: email+password; local: host + token or email/password)
  if (
    (config.somfy?.mode === 'cloud' && config.somfy?.email && config.somfy?.password) ||
    (config.somfy?.host && (config.somfy?.token || (config.somfy?.email && config.somfy?.password)))
  ) {
    const SomfyClient = tryRequire('./src/somfy-client');
    if (SomfyClient) {
      const somfy = new SomfyClient(config, store, sensorRegistry);
      somfy.start().catch((err) => console.error(`[Somfy] Start failed: ${err.message}`));
    }
  }

  // Start Loxone outbound push client if configured
  if (config.loxoneOut?.host && config.loxoneOut?.mappings?.length) {
    const LoxoneOutClient = tryRequire('./src/loxone-out-client');
    if (LoxoneOutClient) {
      const loxoneOut = new LoxoneOutClient(config, store);
      loxoneOut.start();
    }
  }

  // Start AuxAir (AC Freedom) client if configured
  if (config.auxair?.email && config.auxair?.password) {
    const AuxAirClient = tryRequire('./src/auxair-client');
    if (AuxAirClient) {
      const auxair = new AuxAirClient(config, store, sensorRegistry);
      auxair.start().catch((err) => console.error(`[AuxAir] Start failed: ${err.message}`));
    }
  }

  // Start Denon AVR client if configured
  if (config.denon?.host) {
    const DenonClient = tryRequire('./src/denon-client');
    if (DenonClient) {
      const denon = new DenonClient(config, store, sensorRegistry);
      denon.start().catch((err) => console.error(`[Denon] Start failed: ${err.message}`));
    }
  }

  // Start VENTS / Blauberg ventilation client if configured
  if (config.vents?.host) {
    const VentsClient = tryRequire('./src/vents-client');
    if (VentsClient) {
      const vents = new VentsClient(config, store, sensorRegistry);
      vents.start().catch((err) => console.error(`[VENTS] Start failed: ${err.message}`));
    }
  }

  // Start Worx Landroid mower client if configured
  if (config.landroid?.email && config.landroid?.password) {
    const LandroidClient = tryRequire('./src/landroid-client');
    if (LandroidClient) {
      const landroid = new LandroidClient(config, store, sensorRegistry);
      landroid.start().catch((err) => console.error(`[Landroid] Start failed: ${err.message}`));
    }
  }

  // Start Sonos client if configured or auto-discovery enabled
  if (config.sonos) {
    const SonosClient = tryRequire('./src/sonos-client');
    if (SonosClient) {
      const sonos = new SonosClient(config, store, sensorRegistry);
      sonos.start().catch((err) => console.error(`[Sonos] Start failed: ${err.message}`));
    }
  }

  // Start Bayrol Pool Manager client if configured
  if (config.bayrol?.username && config.bayrol?.password) {
    const BayrolClient = tryRequire('./src/bayrol-client');
    if (BayrolClient) {
      const bayrol = new BayrolClient(config, store, sensorRegistry);
      bayrol.start().catch((err) => console.error(`[Bayrol] Start failed: ${err.message}`));
    }
  }

  // Start SmartTub client if configured
  if (config.smarttub?.email && config.smarttub?.password) {
    const SmartTubClient = tryRequire('./src/smarttub-client');
    if (SmartTubClient) {
      const smarttub = new SmartTubClient(config, store, sensorRegistry);
      smarttub.start().catch((err) => console.error(`[SmartTub] Start failed: ${err.message}`));
    }
  }

  // Start SmartBob MQTT client if configured
  if (config.smartbob?.entities?.length) {
    const SmartBobClient = tryRequire('./src/smartbob-client');
    if (SmartBobClient) {
      const smartbob = new SmartBobClient(config, store, sensorRegistry);
      smartbob.start();
    }
  }

  // Start Suppla client if configured
  if (config.suppla?.token) {
    const SuplaClient = tryRequire('./src/suppla-client');
    if (SuplaClient) {
      const suppla = new SuplaClient(config, store, sensorRegistry);
      suppla.start().catch((err) => console.error(`[Suppla] Start failed: ${err.message}`));
    }
  }

  // Start Arduino MQTT client if configured
  if (config.arduino?.devices?.length) {
    const ArduinoClient = tryRequire('./src/arduino-client');
    if (ArduinoClient) {
      const arduino = new ArduinoClient(config, store, sensorRegistry);
      arduino.start();
    }
  }

  // Start Z-Way / RaZberry client if configured
  if (config.zway?.host) {
    const ZWayClient = tryRequire('./src/zway-client');
    if (ZWayClient) {
      const zway = new ZWayClient(config, store, sensorRegistry);
      zway.start().catch((err) => console.error(`[Z-Way] Start failed: ${err.message}`));
    }
  }

  // Start Wiren Board client if configured
  if (config.wirenboard?.host) {
    const WirenBoardClient = tryRequire('./src/wirenboard-client');
    if (WirenBoardClient) {
      const wirenboard = new WirenBoardClient(config, store, sensorRegistry);
      wirenboard.start();
    }
  }

  // Start KNX client if configured
  if (config.knx?.host) {
    const KNXClient = tryRequire('./src/knx-client', 'npm install knx');
    if (KNXClient) {
      const knxClient = new KNXClient(config, store, sensorRegistry);
      knxClient.start().catch((err) => console.error(`[KNX] Start failed: ${err.message}`));
    }
  }

  // Start Fibaro Home Center client if configured
  if (config.fibaro?.host) {
    const FibaroClient = tryRequire('./src/fibaro-client');
    if (FibaroClient) {
      const fibaro = new FibaroClient(config, store, sensorRegistry);
      fibaro.start().catch((err) => console.error(`[Fibaro] Start failed: ${err.message}`));
    }
  }

  // Start Homey client if configured
  if (config.homey?.token && (config.homey?.host || config.homey?.homeyId)) {
    const HomeyClient = tryRequire('./src/homey-client');
    if (HomeyClient) {
      const homey = new HomeyClient(config, store, sensorRegistry);
      homey.start().catch((err) => console.error(`[Homey] Start failed: ${err.message}`));
    }
  }

  // Start Loxone client if configured
  let loxoneClient = null;
  if (config.loxone?.host) {
    const LoxoneClient = tryRequire('./src/loxone-client');
    if (LoxoneClient) {
      loxoneClient = new LoxoneClient(config, store, sensorRegistry);
      loxoneClient.start().catch((err) => console.error(`[Loxone] Start failed: ${err.message}`));
    }
  }

  if (config.homekit?.enabled !== false) {
    const startHomekitBridge = tryRequire('./src/homekit-bridge', 'install hap-nodejs to enable HomeKit');
    if (startHomekitBridge) {
      try {
        startHomekitBridge(config, store, relayController, sensorRegistry, { unifiProtect, loxoneClient, automation });
      } catch (err) {
        console.error(`[HomeKit] Start failed: ${err.message}`);
      }
    }
  }

  const protocol = (mainServer instanceof https.Server) ? 'https' : 'http';
  mainServer.listen(mainPort, () => {
    console.log(`[Server] ${protocol}://localhost:${mainPort}`);
    if (!auth.hasUsers()) {
      console.log('[Server] No users configured — visit /setup.html to create your admin account');
    }
  });
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
