// Wiring emulator phrase book, part 5 (1-Wire / DS18B20): English → [pl, de, fr, es, it, uk].
export const T5 = {
  '{v} on interface pin {t} — the 3.3 V interface would be destroyed.': ['{v} na pinie interfejsu {t} — interfejs 3,3 V uległby zniszczeniu.', '{v} an Schnittstellenpin {t} — die 3,3-V-Schnittstelle würde zerstört.', '{v} sur la broche d’interface {t} — l’interface 3,3 V serait détruite.', '{v} en el pin de interfaz {t} — la interfaz de 3,3 V se destruiría.', '{v} sul pin di interfaccia {t} — l’interfaccia 3,3 V verrebbe distrutta.', '{v} на контакті інтерфейсу {t} — інтерфейс 3,3 В буде знищено.'],
  '1-Wire data is shorted to supply or ground — no sensor can be read.': ['Linia danych 1-Wire jest zwarta z zasilaniem lub masą — żaden czujnik nie zostanie odczytany.', '1-Wire-Datenleitung mit Versorgung oder Masse kurzgeschlossen — kein Sensor lesbar.', 'La donnée 1-Wire est en court-circuit avec l’alimentation ou la masse — aucun capteur n’est lisible.', 'El dato 1-Wire está en corto con la alimentación o masa — no se puede leer ningún sensor.', 'Il dato 1-Wire è in corto con alimentazione o massa — nessun sensore è leggibile.', 'Лінію даних 1-Wire закорочено на живлення або землю — жоден датчик не зчитується.'],
  '{p} is wired the wrong way round (supply and ground swapped) — it overheats and is destroyed.': ['{p} jest podłączony odwrotnie (zamienione zasilanie i masa) — przegrzeje się i ulegnie zniszczeniu.', '{p} ist verpolt (Versorgung und Masse vertauscht) — er überhitzt und wird zerstört.', '{p} est branché à l’envers (alimentation et masse inversées) — il chauffe et est détruit.', '{p} está conectado al revés (alimentación y masa invertidas) — se sobrecalienta y se destruye.', '{p} è collegato al contrario (alimentazione e massa invertite) — si surriscalda e si distrugge.', '{p} під’єднано навпаки (живлення й земля переплутані) — він перегріється й вийде з ладу.'],
  '{p}: parasite power (supply tied to ground) — this example uses the 3-wire connection instead.': ['{p}: zasilanie pasożytnicze (zasilanie połączone z masą) — ten przykład używa połączenia 3-przewodowego.', '{p}: parasitäre Versorgung (Versorgung an Masse) — dieses Beispiel nutzt den 3-Draht-Anschluss.', '{p} : alimentation parasite (alimentation reliée à la masse) — cet exemple utilise le raccordement 3 fils.', '{p}: alimentación parásita (alimentación unida a masa) — este ejemplo usa la conexión de 3 hilos.', '{p}: alimentazione parassita (alimentazione a massa) — questo esempio usa il collegamento a 3 fili.', '{p}: паразитне живлення (живлення з’єднано із землею) — цей приклад використовує 3-провідне підключення.'],
  'Red is used here for supplies (+24 V, sensor 3.3 V), but {w} isn’t a supply.': ['Czerwony oznacza tu zasilanie (+24 V, 3,3 V czujników), a {w} nim nie jest.', 'Rot steht hier für Versorgungen (+24 V, 3,3 V der Sensoren), aber {w} ist keine.', 'Le rouge est utilisé ici pour les alimentations (+24 V, 3,3 V des capteurs), mais {w} n’en est pas une.', 'Aquí el rojo es para alimentaciones (+24 V, 3,3 V de sensores), pero {w} no lo es.', 'Qui il rosso è per le alimentazioni (+24 V, 3,3 V dei sensori), ma {w} non lo è.', 'Червоний тут — для живлення (+24 В, 3,3 В датчиків), але {w} ним не є.'],
  'supply (red)': ['zasilanie (czerwony)', 'Versorgung (rot)', 'alimentation (rouge)', 'alimentación (rojo)', 'alimentazione (rosso)', 'живлення (червоний)'],
  'data (DQ)': ['dane (DQ)', 'Daten (DQ)', 'données (DQ)', 'datos (DQ)', 'dati (DQ)', 'дані (DQ)'],
  'ground': ['masa', 'Masse', 'masse', 'masa', 'massa', 'земля'],
  'offline': ['brak odczytu', 'offline', 'hors ligne', 'sin lectura', 'offline', 'немає зв’язку'],
  'Two DS18B20 temperature sensors (1-Wire)': ['Dwa czujniki temperatury DS18B20 (1-Wire)', 'Zwei DS18B20-Temperatursensoren (1-Wire)', 'Deux capteurs de température DS18B20 (1-Wire)', 'Dos sensores de temperatura DS18B20 (1-Wire)', 'Due sensori di temperatura DS18B20 (1-Wire)', 'Два датчики температури DS18B20 (1-Wire)'],
  'DS18B20 #1': ['DS18B20 #1', 'DS18B20 #1', 'DS18B20 n° 1', 'DS18B20 n.º 1', 'DS18B20 n. 1', 'DS18B20 №1'],
  'DS18B20 #2': ['DS18B20 #2', 'DS18B20 #2', 'DS18B20 n° 2', 'DS18B20 n.º 2', 'DS18B20 n. 2', 'DS18B20 №2'],
  'Interface connector pin 1 — sensor supply, 3.3 V (red wire in the sheet’s example)': ['Złącze interfejsów, pin 1 — zasilanie czujników 3,3 V (czerwony przewód w przykładzie z karty)', 'Schnittstellenstecker Pin 1 — Sensorversorgung 3,3 V (rote Ader im Beispiel des Blatts)', 'Connecteur d’interfaces, broche 1 — alimentation capteurs 3,3 V (fil rouge dans l’exemple de la fiche)', 'Conector de interfaces, pin 1 — alimentación de sensores 3,3 V (cable rojo en el ejemplo de la hoja)', 'Connettore interfacce, pin 1 — alimentazione sensori 3,3 V (filo rosso nell’esempio del foglio)', 'Роз’єм інтерфейсів, контакт 1 — живлення датчиків 3,3 В (червоний провід у прикладі з листка)'],
  'Interface connector pin 4 — 1-Wire data (blue wire in the sheet’s example)': ['Złącze interfejsów, pin 4 — dane 1-Wire (niebieski przewód w przykładzie z karty)', 'Schnittstellenstecker Pin 4 — 1-Wire-Daten (blaue Ader im Beispiel des Blatts)', 'Connecteur d’interfaces, broche 4 — données 1-Wire (fil bleu dans l’exemple de la fiche)', 'Conector de interfaces, pin 4 — datos 1-Wire (cable azul en el ejemplo de la hoja)', 'Connettore interfacce, pin 4 — dati 1-Wire (filo blu nell’esempio del foglio)', 'Роз’єм інтерфейсів, контакт 4 — дані 1-Wire (синій провід у прикладі з листка)'],
  'Interface connector pin 5 — ground (black wire in the sheet’s example)': ['Złącze interfejsów, pin 5 — masa (czarny przewód w przykładzie z karty)', 'Schnittstellenstecker Pin 5 — Masse (schwarze Ader im Beispiel des Blatts)', 'Connecteur d’interfaces, broche 5 — masse (fil noir dans l’exemple de la fiche)', 'Conector de interfaces, pin 5 — masa (cable negro en el ejemplo de la hoja)', 'Connettore interfacce, pin 5 — massa (filo nero nell’esempio del foglio)', 'Роз’єм інтерфейсів, контакт 5 — земля (чорний провід у прикладі з листка)'],
  'DS18B20 sensors share one 1-Wire bus in parallel (each has its own 64-bit address): supply, data and ground to interface pins 1, 4 and 5. The interface is 3.3 V logic — never 24 V or 230 V on it.': ['Czujniki DS18B20 dzielą jedną magistralę 1-Wire równolegle (każdy ma własny 64-bitowy adres): zasilanie, dane i masa do pinów 1, 4 i 5 interfejsu. Interfejs ma logikę 3,3 V — nigdy 24 V ani 230 V.', 'DS18B20-Sensoren teilen sich parallel einen 1-Wire-Bus (jeder hat eine eigene 64-Bit-Adresse): Versorgung, Daten und Masse an Schnittstellenpins 1, 4 und 5. Die Schnittstelle ist 3,3-V-Logik — niemals 24 V oder 230 V.', 'Les capteurs DS18B20 partagent un bus 1-Wire en parallèle (chacun a sa propre adresse 64 bits) : alimentation, données et masse sur les broches 1, 4 et 5. L’interface est en logique 3,3 V — jamais de 24 V ni 230 V.', 'Los sensores DS18B20 comparten un bus 1-Wire en paralelo (cada uno con su dirección de 64 bits): alimentación, datos y masa a los pines 1, 4 y 5. La interfaz es lógica de 3,3 V — nunca 24 V ni 230 V.', 'I sensori DS18B20 condividono un bus 1-Wire in parallelo (ognuno ha il proprio indirizzo a 64 bit): alimentazione, dati e massa ai pin 1, 4 e 5. L’interfaccia è a logica 3,3 V — mai 24 V o 230 V.', 'Датчики DS18B20 паралельно ділять одну шину 1-Wire (кожен має власну 64-бітну адресу): живлення, дані й земля на контакти 1, 4 і 5. Інтерфейс — логіка 3,3 В, ніколи не подавайте 24 В чи 230 В.'],
}
