// Wiring emulator phrase book, part 6 (real module photo): English → [pl, de, fr, es, it, uk].
export const T6 = {
  'Real module': ['Prawdziwy moduł', 'Echtes Modul', 'Module réel', 'Módulo real', 'Modulo reale', 'Справжній модуль'],
  'The photo is loaded from the manuals repository — add the GitHub token in Settings → Device manuals.': ['Zdjęcie pobierane jest z repozytorium instrukcji — dodaj token GitHub w Ustawienia → Device manuals.', 'Das Foto kommt aus dem Anleitungs-Repository — GitHub-Token unter Einstellungen → Device manuals eintragen.', 'La photo vient du dépôt des notices — ajoutez le jeton GitHub dans Réglages → Device manuals.', 'La foto se carga del repositorio de manuales — añade el token de GitHub en Ajustes → Device manuals.', 'La foto viene dal repository dei manuali — aggiungi il token GitHub in Impostazioni → Device manuals.', 'Фото завантажується з репозиторію інструкцій — додайте токен GitHub у Налаштування → Device manuals.'],
  'Outlined: the connectors this diagram uses — click one to zoom.': ['Obrysowane: złącza używane w tym schemacie — kliknij, aby powiększyć.', 'Umrandet: die Stecker, die dieser Schaltplan nutzt — anklicken zum Vergrößern.', 'Encadrés : les connecteurs utilisés par ce schéma — cliquez pour zoomer.', 'Recuadrados: los conectores que usa este esquema — haz clic para ampliar.', 'Evidenziati: i connettori usati da questo schema — clicca per ingrandire.', 'Обведено: роз’єми, які використовує ця схема — клікніть, щоб збільшити.'],
  'Relay outputs (green 5-pin block: NO, COM + NO, COM, NC)': ['Wyjścia przekaźnikowe (zielone złącze 5-pinowe: NO, COM + NO, COM, NC)', 'Relaisausgänge (grüner 5-poliger Stecker: NO, COM + NO, COM, NC)', 'Sorties relais (bornier vert 5 broches : NO, COM + NO, COM, NC)', 'Salidas de relé (bloque verde de 5 pines: NO, COM + NO, COM, NC)', 'Uscite relè (morsettiera verde a 5 pin: NO, COM + NO, COM, NC)', 'Релейні виходи (зелений 5-контактний роз’єм: NO, COM + NO, COM, NC)'],
  'Which block carries which relays is printed on the device.': ['Które złącze obsługuje które przekaźniki, jest nadrukowane na urządzeniu.', 'Welcher Stecker welche Relais führt, ist auf dem Gerät aufgedruckt.', 'Quel bornier porte quels relais est imprimé sur l’appareil.', 'Qué bloque lleva qué relés está impreso en el dispositivo.', 'Quale morsettiera porta quali relè è stampato sul dispositivo.', 'Який роз’єм відповідає яким реле, надруковано на пристрої.'],
  'Inputs (green 8-pin blocks along the top)': ['Wejścia (zielone złącza 8-pinowe u góry)', 'Eingänge (grüne 8-polige Stecker oben)', 'Entrées (borniers verts 8 broches en haut)', 'Entradas (bloques verdes de 8 pines arriba)', 'Ingressi (morsettiere verdi a 8 pin in alto)', 'Входи (зелені 8-контактні роз’єми зверху)'],
  '24 V DC power (orange 2-pin block)': ['Zasilanie 24 V DC (pomarańczowe złącze 2-pinowe)', '24-V-DC-Versorgung (orangefarbener 2-poliger Stecker)', 'Alimentation 24 V CC (bornier orange 2 broches)', 'Alimentación 24 V CC (bloque naranja de 2 pines)', 'Alimentazione 24 V CC (morsettiera arancione a 2 pin)', 'Живлення 24 В DC (помаранчевий 2-контактний роз’єм)'],
  'Interface connector (black 5-pin: 1-Wire, I²C, RS485)': ['Złącze interfejsów (czarne 5-pinowe: 1-Wire, I²C, RS485)', 'Schnittstellenstecker (schwarz, 5-polig: 1-Wire, I²C, RS485)', 'Connecteur d’interfaces (noir 5 broches : 1-Wire, I²C, RS485)', 'Conector de interfaces (negro de 5 pines: 1-Wire, I²C, RS485)', 'Connettore interfacce (nero a 5 pin: 1-Wire, I²C, RS485)', 'Роз’єм інтерфейсів (чорний 5-контактний: 1-Wire, I²C, RS485)'],
}
T6['Terminal {t}'] = ['Zacisk {t}', 'Klemme {t}', 'Borne {t}', 'Borne {t}', 'Morsetto {t}', 'Клема {t}']
T6['Terminal view from the manual'] = ['Widok zacisków z instrukcji', 'Klemmenansicht aus der Anleitung', 'Vue des bornes tirée de la notice', 'Vista de bornes del manual', 'Vista dei morsetti dal manuale', 'Вигляд клем з інструкції']
