#!/data/data/com.termux/files/usr/bin/bash
#
# Installs and starts LSH inside Termux on an Android tablet/phone.
# Run this ON THE DEVICE, inside the Termux app (not from a desktop shell).
#
# What it does:
#   1. Installs Node.js, git, ffmpeg via Termux's package manager (all
#      prebuilt binaries — nothing gets compiled on-device)
#   2. Clones or updates the LSH repo under ~/lsh
#   3. Runs npm install (react-dashboard/dist is committed, so no on-device
#      build step is needed)
#   4. Creates config.json from config.example.json if one doesn't exist yet
#   5. Installs PM2 and starts LSH under it, reusing the repo's existing
#      ecosystem.config.js (same tool used for the Casablanca deploy)
#   6. Writes a Termux:Boot script so LSH restarts automatically after the
#      tablet reboots (only takes effect if the Termux:Boot app is installed
#      — see docs/ANDROID-TABLET-INSTALL.md)
#
# Safe to re-run: pulls latest instead of re-cloning, won't overwrite an
# existing config.json, and pm2 start/reload is idempotent.
#
# Env vars (all optional):
#   REPO_URL   - git remote to clone (default: dagoomax/lsh on GitHub)
#   INSTALL_DIR - where to put it (default: $HOME/lsh)

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/dagoomax/lsh.git}"
INSTALL_DIR="${INSTALL_DIR:-$HOME/lsh}"

log()  { printf '\n\033[1;36m==>\033[0m %s\n' "$1"; }
warn() { printf '\033[1;33m!! \033[0m %s\n' "$1"; }

if [ -z "${PREFIX:-}" ] || [[ "$PREFIX" != *com.termux* ]]; then
  echo "This script must be run inside Termux on the Android device, not on a desktop shell." >&2
  exit 1
fi

log "Updating Termux packages"
pkg update -y && pkg upgrade -y

log "Installing Node.js, git, ffmpeg (prebuilt, no compiling)"
pkg install -y nodejs-lts git ffmpeg

log "Requesting storage/wake-lock helper commands (termux-api)"
pkg install -y termux-api || warn "termux-api package failed to install — wake-lock helper below will be skipped, install it manually later if needed."

if [ -d "$INSTALL_DIR/.git" ]; then
  log "Existing checkout found at $INSTALL_DIR — pulling latest"
  git -C "$INSTALL_DIR" pull --ff-only
else
  log "Cloning $REPO_URL into $INSTALL_DIR"
  git clone "$REPO_URL" "$INSTALL_DIR"
fi

cd "$INSTALL_DIR"

log "Installing npm dependencies (this can take a few minutes on a tablet CPU)"
npm install --no-audit --no-fund

if [ ! -f config.json ]; then
  log "No config.json found — seeding one from config.example.json"
  cp config.example.json config.json
  warn "Edit $INSTALL_DIR/config.json before relying on this — at minimum set server.port and any platform sections you want active."
else
  log "config.json already exists — leaving it untouched"
fi

mkdir -p logs persist

log "Installing PM2 process manager"
npm install -g pm2

log "Starting LSH under PM2 (ecosystem.config.js)"
if pm2 describe lsh >/dev/null 2>&1; then
  pm2 reload ecosystem.config.js
else
  pm2 start ecosystem.config.js
fi
pm2 save

log "Writing Termux:Boot autostart script"
mkdir -p "$HOME/.termux/boot"
cat > "$HOME/.termux/boot/start-lsh.sh" <<EOF
#!$PREFIX/usr/bin/bash
# Auto-generated by install-android-termux.sh — runs when Termux:Boot fires
# on device startup. Requires the separate Termux:Boot app (see
# docs/ANDROID-TABLET-INSTALL.md) and Termux to be excluded from battery
# optimization, or Android will kill this before it does anything useful.
termux-wake-lock 2>/dev/null || true
cd "$INSTALL_DIR"
pm2 resurrect || pm2 start ecosystem.config.js
EOF
chmod +x "$HOME/.termux/boot/start-lsh.sh"

IP="$(ip -4 addr show wlan0 2>/dev/null | awk '/inet /{print $2}' | cut -d/ -f1)"
PORT="$(node -e "try{console.log(require('./config.json').server?.port||3000)}catch(e){console.log(3000)}")"

log "Done."
echo "LSH is running under PM2 in $INSTALL_DIR"
echo "Dashboard: http://${IP:-<tablet-ip>}:${PORT}/react/"
echo
echo "Next steps (see docs/ANDROID-TABLET-INSTALL.md for details):"
echo "  - Exclude Termux from Android's battery optimization"
echo "  - Install the Termux:Boot app so start-lsh.sh runs on device reboot"
echo "  - Run 'termux-wake-lock' once so Android doesn't suspend the process"
echo "  - pm2 logs lsh   /   pm2 status   for day-to-day management"
