'use strict';

const fs    = require('fs');
const path  = require('path');
const http  = require('http');
const https = require('https');
const { buildInputsXml } = require('./loxone-xml');

const TRIGGER_TYPES = ['trigger', 'time', 'mqttIn']; // flow entry-point node types

const AUTOMATIONS_PATH = path.join(__dirname, '..', 'automations.json');
const MAX_NOTIFICATIONS = 200;

// Binary responses fetched by an `http` node with `saveAs` land here — served
// back out by GET /api/flow-snapshots/:name (see api-routes.js). Lets a flow
// pull a JPEG from any URL and use it exactly like a camera's snapshotUrl.
const SNAPSHOTS_DIR = path.join(__dirname, '..', 'persist', 'flow-snapshots');
const MAX_SNAPSHOT_BYTES = 8 * 1024 * 1024; // 8 MB — generous for a JPEG, bounded to avoid runaway memory

// Loxone Virtual Input XML generated by a `loxoneXml` node lands here —
// served back out by GET /api/flow-loxone/:name.xml (api-routes.js). The
// node also auto-registers a throwaway sensor device (type 'flow') so
// /api/devices — which is what Loxone actually polls at runtime — has
// something live to serve; the XML alone is just the one-time import
// artifact that tells Loxone Config where/how to poll it.
const LOXONE_XML_DIR = path.join(__dirname, '..', 'persist', 'flow-loxone');

// Node sends no User-Agent by default, which trips bot-blocking WAFs (e.g.
// CloudFront "Request blocked" 403s) on plenty of ordinary sites. A
// browser-like UA is the difference between an http node working and not,
// for anything scraping a public page rather than hitting a real API.
const HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';
// Text-mode http node cap — was 100KB (too small for a real scraped page,
// e.g. a product listing) and, on top of that, hung forever once hit (see
// _httpRequest). 3MB comfortably covers a full HTML page while staying bounded.
const MAX_TEXT_RESPONSE_BYTES = 3 * 1024 * 1024;

const OPS = {
  '>':  (a, b) => Number(a) >  Number(b),
  '<':  (a, b) => Number(a) <  Number(b),
  '>=': (a, b) => Number(a) >= Number(b),
  '<=': (a, b) => Number(a) <= Number(b),
  '==': (a, b) => String(a) === String(b) || Number(a) === Number(b),
  '!=': (a, b) => String(a) !== String(b) && Number(a) !== Number(b),
};

let nextNotifId = 1;

/**
 * Rules, scenes and notifications.
 *
 * Rule:  { id, name, enabled, trigger: { key, op, value }, actions: [...], cooldownSeconds }
 *   op: > < >= <= == != changes — comparison ops are edge-triggered (fire on
 *   false→true transition); 'changes' fires on every value change.
 * Scene: { id, name, icon, actions: [...] }
 * Action: { type: 'device', deviceKey, sensor, value }
 *       | { type: 'relay',  index, on }
 *       | { type: 'notify', level: 'info'|'warning'|'critical', message }
 *       | { type: 'scene',  sceneId }
 *       | { type: 'page',   from, to }   -- see src/paging.js; from/to are config.paging.rooms ids
 * notify messages support {value} and {key} placeholders.
 */
class AutomationEngine {
  constructor(store, sensorRegistry, relayController, config) {
    this._store    = store;
    this._registry = sensorRegistry;
    this._relays   = relayController;
    this._config   = config || {};
    this._io       = null;
    this._paging   = null; // src/paging.js — set via setPaging() once server.js constructs it

    this.rules  = [];
    this.scenes = [];
    this.flows  = [];
    this.notifications = [];

    this._ruleState = new Map(); // ruleId → { matched: bool, lastFired: ts }
    this._flowState = new Map(); // `${flowId}:${nodeId}` → { matched: bool }
    this._timers    = new Map(); // `${flowId}:${nodeId}` → interval handle (time triggers)
    this._mqtt      = null;      // lazy MQTT client for mqttIn/mqttOut nodes
    this._mqttSubs  = new Map(); // topic → [{ flow, node }]
    this._mqttTopics = new Set();// currently subscribed topics
    this._flowDeviceKeys = new Set(); // flow/<slug>, flowloxone/<slug> keys already registered with sensorRegistry
    this._globals = new Map(); // name → value, shared across every flow's `global` nodes — memory-only (see 'global' node docs below)
  }

  setIo(io) { this._io = io; }
  setPaging(pagingManager) { this._paging = pagingManager; }

  start() {
    this._load();
    this._store.on('change', ({ key, value }) => this._onChange(key, value));
    this._setupTriggers();
    this._registerFlowDevices();
    console.log(`[Automation] Started — ${this.rules.length} rule(s), ${this.scenes.length} scene(s), ${this.flows.length} flow(s)`);
  }

  // `store`/`loxoneXml` nodes only register their device with sensorRegistry
  // (an in-memory, rebuilt-every-boot registry) when they actually execute —
  // so a flow value that showed up on Graphs before a restart silently
  // vanishes from "Flow" until its trigger fires again, which for e.g. an
  // hourly `time` node could be up to an hour (or never, for a disabled
  // flow — but a disabled flow can still be run manually via Test run, and
  // the device it created shouldn't disappear just because a restart
  // happened in between). Pre-register on startup for every flow — enabled
  // or not — so the device (and whatever value survived in the persisted
  // store) is back immediately, not just after the next run.
  _registerFlowDevices() {
    for (const flow of this.flows) {
      for (const node of flow.nodes || []) {
        if (node.type === 'store' && node.config?.name) this._registerFlowDevice(node.config, 'flow');
        else if (node.type === 'loxoneXml' && node.config?.name) this._registerFlowDevice(node.config, 'flowloxone');
      }
    }
  }

  stop() {
    for (const t of this._timers.values()) clearInterval(t);
    this._timers.clear();
    if (this._mqtt) { try { this._mqtt.end(true); } catch {} this._mqtt = null; }
  }

  // ── Non-store triggers: time intervals + MQTT subscriptions ───────────────
  _setupTriggers() {
    // reset interval timers
    for (const t of this._timers.values()) clearInterval(t);
    this._timers.clear();

    const wantTopics = new Set();
    this._mqttSubs = new Map();
    for (const flow of this.flows) {
      if (flow.enabled === false) continue;
      for (const node of flow.nodes || []) {
        if (node.type === 'time') {
          const secs = Math.max(1, Number(node.config?.intervalSeconds) || 60);
          this._timers.set(`${flow.id}:${node.id}`, setInterval(() => {
            this._propagate(flow, node, { payload: Date.now(), source: `flow:${flow.name}` }, 0).catch(() => {});
          }, secs * 1000));
        } else if (node.type === 'mqttIn' && node.config?.topic) {
          const topic = node.config.topic;
          wantTopics.add(topic);
          if (!this._mqttSubs.has(topic)) this._mqttSubs.set(topic, []);
          this._mqttSubs.get(topic).push({ flow, node });
        }
      }
    }
    this._syncMqtt(wantTopics);
  }

  _ensureMqttClient() {
    if (this._mqtt) return this._mqtt;
    if (!this._config?.mqtt?.host) return null;
    let mqtt;
    try { mqtt = require('mqtt'); } catch { console.error('[Automation] mqtt package unavailable'); return null; }
    const url = `mqtt://${this._config.mqtt.host}:${this._config.mqtt.port || 1883}`;
    this._mqtt = mqtt.connect(url, { reconnectPeriod: 5000, connectTimeout: 8000 });
    this._mqtt.on('connect', () => { for (const t of this._mqttTopics) this._mqtt.subscribe(t); });
    this._mqtt.on('error', (e) => console.error(`[Automation] MQTT: ${e.message}`));
    this._mqtt.on('message', (topic, buf) => {
      const subs = this._mqttSubs.get(topic) || [];
      const payload = buf.toString();
      for (const { flow, node } of subs) {
        this._propagate(flow, node, { payload, topic, source: `flow:${flow.name}` }, 0).catch(() => {});
      }
    });
    return this._mqtt;
  }

  _syncMqtt(wantTopics) {
    if (wantTopics.size === 0) {
      if (this._mqtt) for (const t of this._mqttTopics) this._mqtt.unsubscribe(t);
      this._mqttTopics = new Set();
      return;
    }
    const client = this._ensureMqttClient();
    if (!client) { console.warn('[Automation] MQTT node(s) present but no reachable config.mqtt — skipping'); return; }
    for (const t of this._mqttTopics) if (!wantTopics.has(t)) client.unsubscribe(t);
    for (const t of wantTopics) if (!this._mqttTopics.has(t)) client.subscribe(t);
    this._mqttTopics = wantTopics;
  }

  _httpRequest(method, url, body) {
    return new Promise((resolve, reject) => {
      let u;
      try { u = new URL(url); } catch { return reject(new Error('Invalid URL')); }
      const lib = u.protocol === 'https:' ? https : http;
      const payload = body != null ? Buffer.from(String(body)) : null;
      const headers = { 'User-Agent': HTTP_USER_AGENT, ...(payload ? { 'Content-Type': 'application/json', 'Content-Length': payload.length } : {}) };
      const req = lib.request(u, { method, timeout: 10000, headers }, (res) => {
        let raw = '';
        let truncated = false;
        res.on('data', (c) => {
          if (raw.length > MAX_TEXT_RESPONSE_BYTES) { truncated = true; res.destroy(); return; }
          raw += c;
        });
        res.on('end', () => resolve(raw.length ? raw : `HTTP ${res.statusCode}`));
        // res.destroy() above never fires 'end' — without this, a truncated
        // response (e.g. a scraped page over the cap) hangs the promise forever.
        res.on('close', () => { if (truncated) resolve(raw); });
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('Timeout')); });
      if (payload) req.write(payload);
      req.end();
    });
  }

  // Like _httpRequest, but collects the response as a Buffer instead of
  // coercing chunks to a string — required for binary payloads (images).
  _httpRequestBuffer(method, url) {
    return new Promise((resolve, reject) => {
      let u;
      try { u = new URL(url); } catch { return reject(new Error('Invalid URL')); }
      const lib = u.protocol === 'https:' ? https : http;
      const req = lib.request(u, { method, timeout: 10000, headers: { 'User-Agent': HTTP_USER_AGENT } }, (res) => {
        if (res.statusCode < 200 || res.statusCode >= 300) {
          res.resume(); // drain so the socket can be reused
          return reject(new Error(`HTTP ${res.statusCode}`));
        }
        const chunks = [];
        let bytes = 0;
        res.on('data', (c) => {
          bytes += c.length;
          if (bytes > MAX_SNAPSHOT_BYTES) { req.destroy(); return reject(new Error('Response too large (>8MB)')); }
          chunks.push(c);
        });
        res.on('end', () => resolve(Buffer.concat(chunks)));
      });
      req.on('error', reject);
      req.on('timeout', () => { req.destroy(); reject(new Error('Timeout')); });
      req.end();
    });
  }

  // Shared by `store`/`loxoneXml`: idempotently register a throwaway sensor
  // device under `<namespace>/<slug>` so a flow's output becomes a live,
  // graphable entry on /api/devices (history/Graphs/dashboard all pick it up
  // for free — see sensor-registry.js). Registering twice is harmless in
  // itself, but would reset the sensor descriptor (min/max/unit) back to
  // whatever this run's config says, so it's only done once per key.
  _registerFlowDevice(c, namespace) {
    const slug = String(c.name).replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 60) || 'value';
    const key  = `${namespace}/${slug}`;
    if (!this._flowDeviceKeys.has(key)) {
      const min = Number.isFinite(c.min) ? c.min : -1000000;
      const max = Number.isFinite(c.max) ? c.max : 1000000;
      this._registry.registerDevice({
        key, label: c.name, type: 'flow', icon: namespace === 'flowloxone' ? '🧾' : '🧵', homekit: [],
        sensors: [{ path: 'value', name: 'Value', type: 'range', unit: c.unit || '', min, max }],
      });
      this._flowDeviceKeys.add(key);
    }
    return key;
  }

  // ── Persistence ──────────────────────────────────────────────────────────

  _load() {
    try {
      if (fs.existsSync(AUTOMATIONS_PATH)) {
        const data = JSON.parse(fs.readFileSync(AUTOMATIONS_PATH, 'utf8'));
        this.rules  = data.rules  || [];
        this.scenes = data.scenes || [];
        this.flows  = data.flows  || [];
      }
    } catch (err) {
      console.error(`[Automation] Failed to load automations.json: ${err.message}`);
    }
  }

  _save() {
    fs.writeFileSync(AUTOMATIONS_PATH,
      JSON.stringify({ rules: this.rules, scenes: this.scenes, flows: this.flows }, null, 2), 'utf8');
  }

  // ── Rule evaluation ──────────────────────────────────────────────────────

  _onChange(key, value) {
    for (const rule of this.rules) {
      if (!rule.enabled || rule.trigger?.key !== key) continue;
      try {
        this._evaluate(rule, key, value);
      } catch (err) {
        console.error(`[Automation] Rule "${rule.name}" error: ${err.message}`);
      }
    }
    for (const flow of this.flows) {
      if (flow.enabled === false) continue;
      try {
        this._evalFlow(flow, key, value);
      } catch (err) {
        console.error(`[Automation] Flow "${flow.name}" error: ${err.message}`);
      }
    }
  }

  _evaluate(rule, key, value) {
    const state = this._ruleState.get(rule.id) || { matched: false, lastFired: 0 };
    const op = rule.trigger.op;

    let fire = false;
    if (op === 'changes') {
      fire = true;
    } else {
      const cmp = OPS[op];
      if (!cmp) return;
      const matched = cmp(value, rule.trigger.value);
      fire = matched && !state.matched; // edge-triggered
      state.matched = matched;
    }

    const cooldownMs = (rule.cooldownSeconds || 0) * 1000;
    if (fire && Date.now() - state.lastFired >= cooldownMs) {
      state.lastFired = Date.now();
      console.log(`[Automation] Rule fired: ${rule.name} (${key} = ${value})`);
      this.runActions(rule.actions || [], { key, value, source: `rule:${rule.name}` });
    }
    this._ruleState.set(rule.id, state);
  }

  // ── Actions ──────────────────────────────────────────────────────────────

  async runActions(actions, ctx = {}) {
    for (const action of actions) {
      try {
        await this._runAction(action, ctx);
      } catch (err) {
        console.error(`[Automation] Action failed (${action.type}): ${err.message}`);
        this.notify('warning', `Action failed: ${err.message}`, ctx.source);
      }
    }
  }

  async _runAction(action, ctx) {
    switch (action.type) {
      case 'device':
        await this._registry.sendCommand(action.deviceKey, action.sensor, action.value);
        break;
      case 'relay':
        await this._relays.setState(Number(action.index), !!action.on);
        break;
      case 'notify': {
        const msg = String(action.message || '')
          .replace(/\{value\}/g, ctx.value ?? '')
          .replace(/\{key\}/g, ctx.key ?? '');
        this.notify(action.level || 'info', msg, ctx.source);
        break;
      }
      case 'scene': {
        const scene = this.scenes.find((s) => s.id === action.sceneId);
        if (scene) await this.runActions(scene.actions || [], ctx);
        break;
      }
      case 'page': {
        if (!this._paging) throw new Error('Paging not enabled');
        this._paging.startPage(action.from, action.to);
        break;
      }
      default:
        throw new Error(`Unknown action type: ${action.type}`);
    }
  }

  // ── Flows (Node-RED-style node graphs) ───────────────────────────────────
  // Flow: { id, name, enabled, nodes: [Node] }
  // Node: { id, type, x, y, config: {...}, wires: [[targetId, …], …] }
  //   wires[outputPort] = array of downstream node ids. A message
  //   { payload, key, source } is created by a `trigger` node on a matching
  //   store change and propagated along the wires; each node transforms/routes
  //   it and forwards to its outputs. Depth-capped to prevent runaway loops.
  //
  // Node types:
  //   trigger   { key, op, value }   entry; edge-triggered like a rule
  //   condition { op, value }        routes: output 0 = pass, output 1 = else
  //   device    { deviceKey, sensor, value }   run command, pass msg on
  //   virtual   { deviceKey, sensor: 'value', value }   write a virtual device, pass msg on
  //   sync      { sensor, targets, value }  one `device` node's worth of fan-out to a
  //                                   whole *list* of device keys (newline/comma
  //                                   separated) — same sensor + value applied to each,
  //                                   best-effort (one bad target doesn't block the
  //                                   rest). value defaults to msg.payload if blank.
  //                                   For a no-output physical dimmer/switch acting as
  //                                   a remote for a group of real bulbs.
  //   relay     { index, on }        set relay, pass msg on
  //   notify    { level, message }   toast + log, pass msg on
  //   scene     { sceneId }          run a scene, pass msg on
  //   page      { from, to }         start a paging session between two config.paging.rooms ids, pass msg on
  //   delay     { seconds }          wait, then pass msg on
  //   time      { intervalSeconds }  entry; fires on a repeating interval
  //   mqttIn    { topic }            entry; fires on an MQTT message (payload = message)
  //   mqttOut   { topic, payload }   publish an MQTT message, pass msg on
  //   http      { method, url, body, saveAs } outbound HTTP request; response → msg.payload
  //                                   (or, with saveAs: fetch binary + write to
  //                                   persist/flow-snapshots, payload → its /api/flow-snapshots URL)
  //   extract   { pattern, flags, group }  regex match against msg.payload (e.g. scraped
  //                                   HTML); payload → capture group text, or drops the
  //                                   message if no match — for scraping a value out of
  //                                   an http node's response
  //   global    { mode: 'get'|'set', name, value }  a named value shared across every flow
  //                                   (memory-only — resets on restart, unlike `store`,
  //                                   which is backed by the persisted DataStore). 'set':
  //                                   value defaults to msg.payload if left blank, else
  //                                   {value}/{key}-templated; payload → what was stored.
  //                                   'get': payload → the current value (undefined if
  //                                   never set). Use for state one flow computes and
  //                                   another needs — a running count, a mode flag, …
  //   store     { name, unit, min, max }  writes msg.payload into a throwaway sensor
  //                                   device (flow/<slug>) — auto-registered on first
  //                                   run, so it's live on /api/devices (dashboard,
  //                                   history/Graphs, HomeKit-free); pass-through,
  //                                   msg unchanged. The generic building block
  //                                   loxoneXml below is layered on top of
  //   loxoneXml { name, unit, min, max, host, token }  writes msg.payload into a
  //                                   throwaway sensor device (flowloxone/<slug>) — auto-
  //                                   registered on first run, so it's live on
  //                                   /api/devices — and (re)generates its Loxone
  //                                   VirtualInHttp import XML at
  //                                   persist/flow-loxone/<slug>.xml, served at
  //                                   /api/flow-loxone/<slug>.xml; payload → that URL
  //   sceneGen  { name, icon, enabled, actionType, deviceKey, sensor, value, index, on,
  //               level, message }  creates/updates a Scene (flowscene-<slug>, stable id
  //               — reruns overwrite, never duplicate) with one action of the given type
  //               (device/relay/notify — same shapes as those actions); {value}/{key} in
  //               a device value or notify message resolve against the current msg, so
  //               the scene bakes in whatever the flow computed at generation time.
  //               `enabled` (default true) gates whether the scene strip shows it —
  //               see SceneStrip.jsx in the React dashboard. Pass-through, msg unchanged.
  //   debug     { name }             tap: emit the message to the editor + log (sink)

  _evalFlow(flow, key, value) {
    for (const node of flow.nodes || []) {
      if (node.type !== 'trigger' || node.config?.key !== key) continue;
      const op = node.config.op || 'changes';
      const skey = `${flow.id}:${node.id}`;
      const st = this._flowState.get(skey) || { matched: false };
      let fire = false;
      if (op === 'changes') {
        fire = true;
      } else {
        const cmp = OPS[op];
        if (!cmp) continue;
        const matched = cmp(value, node.config.value);
        fire = matched && !st.matched; // edge-triggered
        st.matched = matched;
        this._flowState.set(skey, st);
      }
      if (fire) {
        const msg = { payload: value, key, source: `flow:${flow.name}` };
        this._propagate(flow, node, msg, 0).catch(() => {});
      }
    }
  }

  async _propagate(flow, node, msg, depth) {
    if (depth > 50) { console.warn(`[Automation] Flow "${flow.name}" depth cap hit`); return; }
    let outputs;
    try {
      outputs = await this._execNode(node, msg); // [msgOrNull per output port]
    } catch (err) {
      // A failing node (bad device key, relay error, …) must never crash the
      // server or halt other flows — log, notify, and stop this branch.
      console.error(`[Automation] Flow "${flow.name}" node ${node.id} (${node.type}) failed: ${err.message}`);
      this.notify('warning', `Flow "${flow.name}": ${node.type} node failed — ${err.message}`, msg.source);
      return;
    }
    const wires = node.wires || [];
    for (let port = 0; port < outputs.length; port++) {
      const outMsg = outputs[port];
      if (outMsg == null) continue;
      for (const targetId of wires[port] || []) {
        const target = (flow.nodes || []).find((n) => n.id === targetId);
        // fire-and-forget branch; _propagate handles its own errors internally
        if (target) this._propagate(flow, target, { ...outMsg }, depth + 1).catch(() => {});
      }
    }
  }

  /** Run a node; return an array of messages, one per output port (null = no emit). */
  async _execNode(node, msg) {
    const c = node.config || {};
    switch (node.type) {
      case 'trigger':
        return [msg]; // single output
      case 'extract': {
        if (!c.pattern) return [null];
        let re;
        try { re = new RegExp(c.pattern, c.flags || ''); }
        catch (err) { throw new Error(`Bad regex: ${err.message}`); }
        const m = re.exec(String(msg.payload ?? ''));
        if (!m) return [null]; // no match — stop this branch, same as a failed condition
        const group = Number.isFinite(c.group) ? c.group : (Number(c.group) || 1);
        return [{ ...msg, payload: m[group] ?? m[0] }];
      }
      case 'condition': {
        const cmp = OPS[c.op];
        const pass = cmp ? cmp(msg.payload, c.value) : false;
        return [pass ? msg : null, pass ? null : msg]; // [then, else]
      }
      case 'device':
        await this._registry.sendCommand(c.deviceKey, c.sensor, resolveTemplate(c.value, msg));
        return [msg];
      case 'virtual':
        // Same mechanism as 'device' — a virtual device is just a device
        // registered by VirtualClient — but scoped to a friendly picker in
        // the editor instead of a free-text key/sensor pair.
        await this._registry.sendCommand(c.deviceKey, c.sensor || 'value', resolveTemplate(c.value, msg));
        return [msg];
      case 'global': {
        if (!c.name) throw new Error('Global node needs a name');
        if (c.mode === 'set') {
          const val = (c.value !== undefined && c.value !== '') ? resolveTemplate(c.value, msg) : msg.payload;
          this._globals.set(c.name, val);
          return [{ ...msg, payload: val }];
        }
        return [{ ...msg, payload: this._globals.get(c.name) }]; // 'get' (default) — undefined if never set
      }
      case 'sync': {
        // Fan a single value out to a whole group of devices in one node —
        // built for a no-load physical dimmer/switch (power+neutral only, no
        // output of its own) whose trigger value should mirror onto one or
        // many real bulbs, instead of wiring a separate `device` node per bulb.
        const sensor  = c.sensor || 'switch';
        const targets = String(c.targets || '').split(/\r?\n|,/).map((s) => s.trim()).filter(Boolean);
        const val     = resolveTemplate((c.value !== undefined && c.value !== '') ? c.value : '{value}', msg);
        for (const deviceKey of targets) {
          try { await this._registry.sendCommand(deviceKey, sensor, val); }
          catch (err) { console.error(`[Automation] Sync target "${deviceKey}" failed: ${err.message}`); }
        }
        return [msg];
      }
      case 'store': {
        if (!c.name) throw new Error('Store node needs a name');
        const key = this._registerFlowDevice(c, 'flow');
        const num = Number(msg.payload);
        this._store.update(`${key}/value`, Number.isNaN(num) ? String(msg.payload ?? '') : num);
        return [msg];
      }
      case 'loxoneXml': {
        if (!c.name) throw new Error('Loxone XML node needs a name');
        const key  = this._registerFlowDevice(c, 'flowloxone');
        const slug = key.split('/')[1];

        const num = Number(msg.payload);
        this._store.update(`${key}/value`, Number.isNaN(num) ? String(msg.payload ?? '') : num);

        const device = (this._registry.getDevices?.() || []).find((d) => d.key === key);
        const host   = c.host  || `localhost:${this._config?.server?.port || 3001}`;
        const token  = c.token || 'YOUR_API_TOKEN';
        const xmlParts = device ? buildInputsXml([device], { host, token }) : [];
        if (xmlParts.length) {
          fs.mkdirSync(LOXONE_XML_DIR, { recursive: true });
          fs.writeFileSync(path.join(LOXONE_XML_DIR, `${slug}.xml`), xmlParts.join('\n'), 'utf8');
        }
        return [{ ...msg, payload: `/api/flow-loxone/${slug}.xml` }];
      }
      case 'sceneGen': {
        if (!c.name) throw new Error('Scene Generator node needs a name');
        const slug = String(c.name).replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 60) || 'scene';
        const id   = `flowscene-${slug}`; // stable id: reruns update the same scene, never duplicate it

        let action;
        switch (c.actionType || 'device') {
          case 'device':
            action = { type: 'device', deviceKey: c.deviceKey, sensor: c.sensor, value: resolveTemplate(c.value, msg) };
            break;
          case 'relay':
            action = { type: 'relay', index: Number(c.index), on: !!c.on };
            break;
          case 'notify':
            action = {
              type: 'notify', level: c.level || 'info',
              message: String(c.message || '').replace(/\{value\}/g, msg.payload ?? '').replace(/\{key\}/g, msg.key ?? ''),
            };
            break;
          default:
            throw new Error(`Scene Generator: unknown action type "${c.actionType}"`);
        }

        this.saveScene({ id, name: c.name, icon: c.icon || '🎬', enabled: c.enabled !== false, actions: [action] });
        return [msg];
      }
      case 'relay':
        await this._relays.setState(Number(c.index), !!c.on);
        return [msg];
      case 'notify': {
        const text = String(c.message || '')
          .replace(/\{value\}/g, msg.payload ?? '')
          .replace(/\{key\}/g, msg.key ?? '');
        this.notify(c.level || 'info', text, msg.source);
        return [msg];
      }
      case 'scene': {
        const scene = this.scenes.find((s) => s.id === c.sceneId);
        if (scene) await this.runActions(scene.actions || [], msg);
        return [msg];
      }
      case 'page': {
        if (!this._paging) throw new Error('Paging not enabled');
        if (!c.from || !c.to) throw new Error('Page node needs both a "from" and "to" room');
        this._paging.startPage(c.from, c.to);
        return [msg];
      }
      case 'delay':
        await new Promise((r) => setTimeout(r, (Number(c.seconds) || 0) * 1000));
        return [msg];
      case 'time':
        return [msg]; // entry node; fired by its interval
      case 'mqttIn':
        return [msg]; // entry node; fired on an incoming message
      case 'http': {
        const method = (c.method || 'GET').toUpperCase();
        if (c.saveAs) {
          // Fetch as binary and stash it under persist/flow-snapshots — lets a
          // flow pull a JPEG from any URL and use it like a camera's
          // snapshotUrl (GET /api/flow-snapshots/<saveAs>).
          const name = sanitizeSnapshotName(c.saveAs);
          const buf  = await this._httpRequestBuffer(method, c.url);
          fs.mkdirSync(SNAPSHOTS_DIR, { recursive: true });
          fs.writeFileSync(path.join(SNAPSHOTS_DIR, `${name}.jpg`), buf);
          return [{ ...msg, payload: `/api/flow-snapshots/${name}.jpg` }];
        }
        const body = c.body ? String(c.body).replace(/\{value\}/g, msg.payload ?? '') : undefined;
        const resp = await this._httpRequest(method, c.url, method === 'GET' ? undefined : body);
        return [{ ...msg, payload: resp }];
      }
      case 'mqttOut': {
        const client = this._ensureMqttClient();
        if (client && c.topic) {
          const pl = String(c.payload ?? msg.payload ?? '').replace(/\{value\}/g, msg.payload ?? '');
          client.publish(c.topic, pl);
        }
        return [msg];
      }
      case 'debug': {
        // Node-RED-style debug tap: surface the message to the editor + log. Sink.
        const label = c.name || 'debug';
        console.log(`[Flow debug] ${label}: ${msg.key ?? ''} = ${JSON.stringify(msg.payload)}`);
        if (this._io) this._io.emit('flow-debug', {
          time: Date.now(), label, key: msg.key ?? null, payload: msg.payload, source: msg.source || null,
        });
        return []; // no output — it's a terminal tap
      }
      default:
        return [msg];
    }
  }

  saveFlow(flow) {
    if (!flow.name) throw new Error('Flow needs a name');
    if (!flow.id) flow.id = `f${Date.now().toString(36)}`;
    if (flow.enabled === undefined) flow.enabled = true;
    if (!Array.isArray(flow.nodes)) flow.nodes = [];
    const idx = this.flows.findIndex((f) => f.id === flow.id);
    if (idx >= 0) this.flows[idx] = flow; else this.flows.push(flow);
    // reset edge-trigger memory for this flow's nodes
    for (const k of [...this._flowState.keys()]) if (k.startsWith(`${flow.id}:`)) this._flowState.delete(k);
    this._save();
    this._setupTriggers(); // (re)establish time/MQTT triggers
    return flow;
  }

  deleteFlow(id) {
    this.flows = this.flows.filter((f) => f.id !== id);
    for (const k of [...this._flowState.keys()]) if (k.startsWith(`${id}:`)) this._flowState.delete(k);
    this._save();
    this._setupTriggers();
  }

  /** Manually fire a flow from its trigger node(s) — used by the editor's "Test run". */
  async runFlow(id) {
    const flow = this.flows.find((f) => f.id === id);
    if (!flow) throw new Error('Flow not found');
    for (const node of flow.nodes || []) {
      if (!TRIGGER_TYPES.includes(node.type)) continue;
      const payload = node.config?.key ? this._store.get(node.config.key) : Date.now();
      await this._propagate(flow, node, { payload, key: node.config?.key, source: `flow-test:${flow.name}` }, 0);
    }
    return flow;
  }

  // ── Notifications ────────────────────────────────────────────────────────

  notify(level, message, source) {
    const entry = { id: nextNotifId++, time: Date.now(), level, message, source: source || null };
    this.notifications.push(entry);
    if (this.notifications.length > MAX_NOTIFICATIONS) this.notifications.shift();
    if (this._io) this._io.emit('notification', entry);
    console.log(`[Automation] [${level}] ${message}`);
    return entry;
  }

  getNotifications() { return this.notifications; }
  clearNotifications() { this.notifications = []; }

  // ── CRUD ─────────────────────────────────────────────────────────────────

  saveRule(rule) {
    if (!rule.name || !rule.trigger?.key || !rule.trigger?.op) throw new Error('Rule needs name, trigger.key and trigger.op');
    if (!rule.id) rule.id = `r${Date.now().toString(36)}`;
    if (rule.enabled === undefined) rule.enabled = true;
    const idx = this.rules.findIndex((r) => r.id === rule.id);
    if (idx >= 0) this.rules[idx] = rule; else this.rules.push(rule);
    this._ruleState.delete(rule.id);
    this._save();
    return rule;
  }

  deleteRule(id) {
    this.rules = this.rules.filter((r) => r.id !== id);
    this._ruleState.delete(id);
    this._save();
  }

  saveScene(scene) {
    if (!scene.name) throw new Error('Scene needs a name');
    if (!scene.id) scene.id = `s${Date.now().toString(36)}`;
    const idx = this.scenes.findIndex((s) => s.id === scene.id);
    if (idx >= 0) this.scenes[idx] = scene; else this.scenes.push(scene);
    this._save();
    return scene;
  }

  deleteScene(id) {
    this.scenes = this.scenes.filter((s) => s.id !== id);
    this._save();
  }

  async runScene(id) {
    const scene = this.scenes.find((s) => s.id === id);
    if (!scene) throw new Error('Scene not found');
    console.log(`[Automation] Scene run: ${scene.name}`);
    await this.runActions(scene.actions || [], { source: `scene:${scene.name}` });
    return scene;
  }
}

// `device`/`virtual` node value field: exact "{value}" preserves the live
// msg.payload's type (so a scraped number lands as a number, not a string,
// which matters for a virtual `sensor` device feeding history/Loxone/etc.);
// a value containing {value}/{key} elsewhere does text substitution like
// notify/mqttOut/http already do; anything else is a static literal
// (existing flows using e.g. "on"/"off" keep working unchanged).
function resolveTemplate(value, msg) {
  if (value === '{value}') return msg.payload;
  if (typeof value === 'string' && (value.includes('{value}') || value.includes('{key}'))) {
    return value.replace(/\{value\}/g, msg.payload ?? '').replace(/\{key\}/g, msg.key ?? '');
  }
  return value;
}

// Shared with api-routes.js (GET /api/flow-snapshots/:name) so the write path
// (here) and read path (there) always agree on what a valid filename is —
// alphanumeric/dash/underscore only, so it can't escape SNAPSHOTS_DIR.
function sanitizeSnapshotName(name) {
  const safe = String(name || '').replace(/[^a-zA-Z0-9_-]/g, '_').slice(0, 100);
  if (!safe) throw new Error('saveAs must contain at least one valid character');
  return safe;
}

module.exports = AutomationEngine;
module.exports.SNAPSHOTS_DIR = SNAPSHOTS_DIR;
module.exports.LOXONE_XML_DIR = LOXONE_XML_DIR;
module.exports.sanitizeSnapshotName = sanitizeSnapshotName;
