// Integration modules on demand. A fresh install ships only the core (see
// modules.json → core, generated by scripts/gen-modules-manifest.js); each
// integration's files are fetched from GitHub the first time it's needed and
// its npm deps installed alongside.
//
// Two triggers:
//   - startup: ensureConfigured(config) fetches every module whose config
//     section is set but whose files/deps are missing
//   - Settings → Modules: install(id) / update(id) via /api/modules
//
// Files come from the git tag matching package.json's version (e.g. v1.31.0), so
// modules stay in step with the core they were released with; if that tag
// doesn't exist yet, main.
//
// npm deps are installed with --no-save so package.json stays the tracked,
// core-only file. npm prunes anything not in package.json on every install,
// so each call passes the deps of *every* installed module, not just the new
// one — the installed set lives in persist/modules.json.

const fs   = require('fs');
const path = require('path');
const https = require('https');
const { execFile } = require('child_process');

const ROOT          = path.join(__dirname, '..');
const MANIFEST_PATH = path.join(ROOT, 'modules.json');
const STATE_PATH    = path.join(ROOT, 'persist', 'modules.json');
const { version }   = require('../package.json');

const FETCH_TIMEOUT_MS = 15000;
const NPM_TIMEOUT_MS   = 10 * 60 * 1000; // tfjs / matter are big

let manifest = null;
function getManifest() {
  if (!manifest) manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));
  return manifest;
}

function readState() {
  try { return JSON.parse(fs.readFileSync(STATE_PATH, 'utf8')); } catch { return { installed: {} }; }
}
function writeState(state) {
  fs.mkdirSync(path.dirname(STATE_PATH), { recursive: true });
  fs.writeFileSync(STATE_PATH, JSON.stringify(state, null, 2));
}

// mod.when is the exact `if (…)` condition server.js loads the module under
// (extracted by scripts/gen-modules-manifest.js) — not just "key present",
// since config.js fills in empty default sections for many integrations.
const whenFns = new Map();
function isConfigured(mod, config) {
  if (!mod.when) return false;
  let fn = whenFns.get(mod.when);
  if (!fn) {
    fn = new Function('config', `try { return !!(${mod.when}); } catch { return false; }`);
    whenFns.set(mod.when, fn);
  }
  return fn(config);
}

function depInstalled(name) {
  // package.json is always resolvable, even for ESM-only packages whose
  // main entry require.resolve() would reject
  try { require.resolve(`${name}/package.json`, { paths: [ROOT] }); return true; }
  catch { return fs.existsSync(path.join(ROOT, 'node_modules', name, 'package.json')); }
}

function moduleStatus(id, mod, config, state) {
  const missingFiles = mod.files.filter((f) => !fs.existsSync(path.join(ROOT, f)));
  const missingDeps  = Object.keys(mod.deps).filter((d) => !depInstalled(d));
  return {
    id,
    configKeys: mod.configKeys,
    configured: isConfigured(mod, config),
    installed: missingFiles.length === 0 && missingDeps.length === 0,
    missingFiles,
    missingDeps,
    deps: Object.keys(mod.deps),
    ref: state.installed[id]?.ref || null,
    installedAt: state.installed[id]?.at || null,
  };
}

function list(config) {
  const state = readState();
  return Object.entries(getManifest().modules).map(([id, mod]) => moduleStatus(id, mod, config, state));
}

// ── GitHub ────────────────────────────────────────────────────────────────

function githubGet(apiPath, token) {
  return new Promise((resolve, reject) => {
    const headers = {
      'User-Agent': 'LSH-module-manager',
      'Accept': 'application/vnd.github.raw+json',
      'X-GitHub-Api-Version': '2022-11-28',
    };
    if (token) headers.Authorization = `Bearer ${token}`;
    const req = https.get({ host: 'api.github.com', path: apiPath, headers, timeout: FETCH_TIMEOUT_MS }, (res) => {
      const chunks = [];
      res.on('data', (c) => chunks.push(c));
      res.on('end', () => resolve({ status: res.statusCode, headers: res.headers, body: Buffer.concat(chunks) }));
    });
    req.on('timeout', () => req.destroy(new Error(`GitHub request timed out: ${apiPath}`)));
    req.on('error', reject);
  });
}

let resolvedRef = null;
async function resolveRef(repo, token) {
  if (resolvedRef) return resolvedRef;
  const tag = `v${version}`;
  const r = await githubGet(`/repos/${repo}/git/ref/tags/${encodeURIComponent(tag)}`, token);
  if (r.status === 200) resolvedRef = tag;
  else if (r.status === 404) {
    console.warn(`[Modules] Tag ${tag} not found on ${repo} — fetching modules from main`);
    resolvedRef = 'main';
  } else {
    throw new Error(`GitHub ${r.status} resolving ${tag}: ${rateLimitHint(r) || r.body.toString().slice(0, 200)}`);
  }
  return resolvedRef;
}

function rateLimitHint(r) {
  if (r.status === 403 && r.headers['x-ratelimit-remaining'] === '0') {
    const reset = new Date(Number(r.headers['x-ratelimit-reset']) * 1000);
    return `GitHub API rate limit hit (resets ${reset.toLocaleTimeString()}) — set modules.githubToken in config.json to raise it`;
  }
  return null;
}

async function fetchFile(repo, ref, file, token) {
  const apiPath = `/repos/${repo}/contents/${file.split('/').map(encodeURIComponent).join('/')}?ref=${encodeURIComponent(ref)}`;
  const r = await githubGet(apiPath, token);
  if (r.status !== 200) {
    throw new Error(`GitHub ${r.status} fetching ${file}@${ref}${rateLimitHint(r) ? ' — ' + rateLimitHint(r) : ''}`);
  }
  if (!r.body.length) throw new Error(`Empty response for ${file}@${ref}`);
  return r.body;
}

// ── npm ───────────────────────────────────────────────────────────────────

function npmInstall(specs) {
  return new Promise((resolve, reject) => {
    const npm = process.platform === 'win32' ? 'npm.cmd' : 'npm';
    const args = ['install', '--no-save', '--no-audit', '--no-fund', '--omit=dev', ...specs];
    console.log(`[Modules] npm ${args.join(' ')}`);
    execFile(npm, args, { cwd: ROOT, timeout: NPM_TIMEOUT_MS, maxBuffer: 16 * 1024 * 1024 }, (err, stdout, stderr) => {
      if (err) return reject(new Error(`npm install failed: ${(stderr || err.message).trim().split('\n').slice(-5).join(' | ')}`));
      resolve(stdout);
    });
  });
}

// Every dep of every module that's installed, configured, or being added —
// see the --no-save note at the top of this file. Configured counts too so a
// module whose deps came from an older full package.json (never recorded in
// state) isn't pruned by someone else's install.
function allWantedDepSpecs(state, config, extraIds) {
  const mods = getManifest().modules;
  const configured = Object.keys(mods).filter((id) => isConfigured(mods[id], config));
  const specs = new Map();
  for (const id of new Set([...Object.keys(state.installed), ...configured, ...extraIds])) {
    for (const [name, ver] of Object.entries(mods[id]?.deps || {})) specs.set(name, `${name}@${ver}`);
  }
  return [...specs.values()];
}

// ── Install ───────────────────────────────────────────────────────────────

// Serialized: two concurrent npm installs in one tree corrupt each other.
let queue = Promise.resolve();
function serialized(fn) {
  const run = queue.then(fn, fn);
  queue = run.catch(() => {});
  return run;
}

// ids: modules to install. force: re-fetch files even if present (update).
function install(ids, config, { force = false } = {}) {
  return serialized(async () => {
    const m = getManifest();
    const unknown = ids.filter((id) => !m.modules[id]);
    if (unknown.length) throw new Error(`Unknown module(s): ${unknown.join(', ')}`);

    const token = config.modules?.githubToken || process.env.GITHUB_TOKEN || null;
    const state = readState();
    let ref = null;

    for (const id of ids) {
      const mod = m.modules[id];
      const files = force ? mod.files : mod.files.filter((f) => !fs.existsSync(path.join(ROOT, f)));
      if (!files.length) continue;
      ref = ref || await resolveRef(m.repo, token);
      // Fetch everything first, then write — a module half-written to disk
      // would look "installed" to the existsSync check next startup.
      const fetched = await Promise.all(files.map(async (f) => [f, await fetchFile(m.repo, ref, f, token)]));
      for (const [f, buf] of fetched) {
        const dest = path.join(ROOT, f);
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.writeFileSync(`${dest}.tmp`, buf);
        fs.renameSync(`${dest}.tmp`, dest);
      }
      console.log(`[Modules] ${id}: fetched ${files.length} file(s) from ${m.repo}@${ref}`);
    }

    const needDeps = ids.some((id) => Object.keys(m.modules[id].deps).some((d) => !depInstalled(d)));
    if (needDeps) await npmInstall(allWantedDepSpecs(state, config, ids));

    const now = new Date().toISOString();
    for (const id of ids) {
      state.installed[id] = { ref: ref || state.installed[id]?.ref || 'local', at: now };
    }
    writeState(state);
    return ids.map((id) => moduleStatus(id, m.modules[id], config, state));
  });
}

// Startup: make sure every configured module is present. Never throws — a
// failed fetch (offline box, rate limit) just leaves that integration
// unavailable, exactly like a missing optional dependency always has.
async function ensureConfigured(config) {
  if (config.modules?.autoInstall === false) return;
  let m;
  try { m = getManifest(); }
  catch (err) { console.warn(`[Modules] modules.json unreadable — skipping auto-install: ${err.message}`); return; }

  const state = readState();
  const needed = Object.entries(m.modules)
    .filter(([id, mod]) => isConfigured(mod, config) && !moduleStatus(id, mod, config, state).installed)
    .map(([id]) => id);
  if (!needed.length) return;

  console.log(`[Modules] Installing configured module(s): ${needed.join(', ')}`);
  try {
    await install(needed, config);
  } catch (err) {
    console.error(`[Modules] Auto-install failed: ${err.message}`);
  }
}

module.exports = { list, install, ensureConfigured };
